### ISSUE TITLE
Create "grouped" curriculum view

### ISSUE THREAD

**Issue by klieret** [hsf-training/training-center#28]
New datafile

```yaml
- id: default
  groups:
      - title: "Software Basics"
         modules:
         - git
         - python
         - bash
     - title: "Software Development and Deployment"
        modules: 
        - git
        - advanced git
        - ci/cd (gitlab)
        - ci/cd (github)
```

For now, let's just create one curriculum "default" that is displayed on a separate tab of the main view
